version: '1'
services:
  # neo4j-store:
  #   build: "./data/"
  backend:
    build: "backend/"
    env_file:
      - "backend/.env"
    ports:
      - 8250:8250
  frontend:
    build: "frontend/"
    env_file:
      - "frontend/.env"
    ports:
      - 8650:8650
