services:
  neo4j-dbms:
    build: "data/"
    ports:
      - 7474:7474
      - 7687:7687
    env_file:
      - "data/.env"
  backend:
    build: "backend/"
    env_file:
      - "backend/.env"
    ports:
      - 8250:8250
  frontend:
    build: "frontend/"
    env_file:
      - "frontend/.env"
    ports:
      - 8650:8650
