name: Lint Frontend

on:
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Move to frontend directory
        run: |
          echo "Before Move"
          ls
          cd ./frontend
          echo "After Move"
          ls

      # - name: Install dependencies
      #   run: npm install

      # - name: Lint
      #   run: npm run lint