name: Lint Backend
on: 
  pull_request:

jobs:
  linting:
    name: Linting Backend
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Lint
        uses: chartboost/ruff-action@v1
        with:
          src: ./backend
